Disable pull request trigger and test status job
Comment out pull request trigger and test status job in workflow.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,8 +1,8 @@
 name: Testing
 
 on:
-  pull_request:
-    branches: ["main"]
+  # pull_request:
+  #   branches: ["main"]
   workflow_dispatch:
 
 jobs:
@@ -17,14 +17,7 @@ jobs:
             arch: amd64
             base_image: "ubuntu:22.04"
             runner: ubuntu-latest
-          - target: cpu
-            arch: arm64
-            base_image: "ubuntu:22.04"
-            runner: ubuntu-24.04-arm
-          - target: gpu
-            arch: amd64
-            base_image: "nvidia/cuda:12.1.1-devel-ubuntu22.04"
-            runner: ubuntu-latest
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -62,15 +55,15 @@ jobs:
           OMPI_MCA_rmaps_base_oversubscribe: 1
           IBLGF_MPI_NP: 4
 
-  test-status:
-    name: Test Status
-    runs-on: ubuntu-latest
-    needs: build-and-test
-    if: always()
-    steps:
-      - name: Enforce all matrix jobs passed
-        run: |
-          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
-            echo "One or more build/test jobs failed."
-            exit 1
-          fi
+  # test-status:
+  #   name: Test Status
+  #   runs-on: ubuntu-latest
+  #   needs: build-and-test
+  #   if: always()
+  #   steps:
+  #     - name: Enforce all matrix jobs passed
+  #       run: |
+  #         if [ "${{ needs.build-and-test.result }}" != "success" ]; then
+  #           echo "One or more build/test jobs failed."
+  #           exit 1
+  #         fi
